export const telegramUserSchema = {
  bgColor: "var(--tg-theme-bg-color)",
  textColor: "var(--tg-theme-text-color)",
  hintColor: "var(--tg-theme-hint-color)",
  linkColor: "var(--tg-theme-link-color)",
  buttonColor: "var(--tg-theme-button-color)",
  buttonTextColor: "var(--tg-theme-button-text-color)",
  secondaryBgColor: "var(--tg-theme-secondary-bg-color)",
  headerBgColor: "var(--tg-theme-header-bg-color)",
  accentTextColor: "var(--tg-theme-accent-text-color)",
  sectionBgColor: "var(--tg-theme-section-bg-color)",
  sectionHeaderTextColor: "var(--tg-theme-section-header-text-color)",
  subtitleTextColor: "var(--tg-theme-subtitle-text-color)",
  destructiveTextColor: "var(--tg-theme-destructive-text-color)",
};
